### ISSUE TITLE
Syntaxes not working and no error messages 

### ISSUE THREAD

**Issue by Vulqa** [TheLimeGlass/Skungee#23] opened 2018-11-05 11:14 UTC
Hi,

I had the opportunity to test several syntaxes, but certain of them do not work and do not give me a error message.

Exemples:
```
command /online <text>:
	trigger:
		if bungeecord player "%arg-1%" is online:
			message "&aYes!"
		else:
			message "&cNo!" #return me always "No!"

command /currentserver <text>:
	trigger:
		set {_server} to "%arg-1%"'s current bungeecord server
		message "%{_server}%" #return me "<none>"

command /hieveryone <text>:
	trigger:
		send "%arg-1%" to all bungeecord players #do nothing

```

My skript's version: 2.3-beta1
My server's version:  1.12.2 (http://prntscr.com/lekdi2)
My bungeecord's version: http://prntscr.com/lekdts
My Skungee's version: 1.0.7d

**Comment by TheLimeGlass** [comment] 2018-12-14 11:06
Duplicate of https://github.com/TheLimeGlass/Skungee/issues/21

**Closed by TheLimeGlass** 2018-12-14 11:06 UTC
